-- Generated by tools/blender (outfit.py). Do not edit by hand.
-- each piece is centred on its reference body part (see outfit.py), character facing -Z
return {
	["NinjaBelt__Obi"] = { Center = Vector3.new(0.0000, -0.4427, -0.1024), Size = Vector3.new(2.2200, 1.2928, 1.4249), Tris = 792, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaBracer__Plate"] = { Center = Vector3.new(0.5811, -0.0609, 0.0000), Size = Vector3.new(0.1777, 0.6418, 1.0113), Tris = 152, Color = Color3.fromRGB(150, 155, 165), Material = Enum.Material.Metal },
	["NinjaBracer__Strap"] = { Center = Vector3.new(0.0000, -0.1000, 0.0000), Size = Vector3.new(1.2600, 0.6400, 1.2600), Tris = 768, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaBracer__Wrap"] = { Center = Vector3.new(0.0000, -0.0907, 0.0000), Size = Vector3.new(1.2498, 0.8215, 1.2498), Tris = 384, Color = Color3.fromRGB(40, 40, 52), Material = Enum.Material.Fabric },
	["NinjaCape__Cloth"] = { Center = Vector3.new(-0.0071, -0.9151, 0.6075), Size = Vector3.new(2.9741, 3.5108, 0.7449), Tris = 1016, Color = Color3.fromRGB(40, 40, 52), Material = Enum.Material.Fabric },
	["NinjaCape__Hem"] = { Center = Vector3.new(0.0000, -0.8550, 0.6168), Size = Vector3.new(2.9804, 3.6300, 0.8336), Tris = 292, Color = Color3.fromRGB(255, 220, 120), Material = Enum.Material.Neon },
	["NinjaGi__Lapel"] = { Center = Vector3.new(-0.0000, 0.0169, 0.0035), Size = Vector3.new(1.0234, 1.7541, 1.1370), Tris = 200, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaHalo__Ring"] = { Center = Vector3.new(0.0000, 1.0500, 0.0000), Size = Vector3.new(1.5400, 0.0900, 1.4668), Tris = 824, Color = Color3.fromRGB(255, 220, 120), Material = Enum.Material.Neon },
	["NinjaHood__Band"] = { Center = Vector3.new(0.0000, 0.1208, 0.3739), Size = Vector3.new(1.5898, 0.5654, 2.4077), Tris = 568, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaHood__Cloth"] = { Center = Vector3.new(0.0000, -0.0095, 0.0304), Size = Vector3.new(1.6254, 1.6229, 1.5392), Tris = 3320, Color = Color3.fromRGB(40, 40, 52), Material = Enum.Material.Fabric },
	["NinjaHood__Eyes"] = { Center = Vector3.new(0.0000, 0.0271, -0.6100), Size = Vector3.new(0.6338, 0.1094, 0.1100), Tris = 104, Color = Color3.fromRGB(255, 255, 255), Material = Enum.Material.Neon },
	["NinjaHood__Mask"] = { Center = Vector3.new(0.0000, -0.3942, -0.4661), Size = Vector3.new(1.5101, 0.5283, 0.6777), Tris = 1004, Color = Color3.fromRGB(26, 26, 34), Material = Enum.Material.Fabric },
	["NinjaHood__Plate"] = { Center = Vector3.new(0.0000, 0.2912, -0.8199), Size = Vector3.new(0.9313, 0.1525, 0.0900), Tris = 84, Color = Color3.fromRGB(150, 155, 165), Material = Enum.Material.Metal },
	["NinjaHorns__Horn"] = { Center = Vector3.new(0.0000, 0.7315, -0.0773), Size = Vector3.new(1.3537, 0.5511, 0.5051), Tris = 1032, Color = Color3.fromRGB(235, 225, 205), Material = Enum.Material.SmoothPlastic },
	["NinjaScarf__Cloth"] = { Center = Vector3.new(0.0000, 0.4816, 1.1495), Size = Vector3.new(1.3573, 1.3041, 3.4568), Tris = 760, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaShin__Plate"] = { Center = Vector3.new(0.0000, 0.1493, -0.4475), Size = Vector3.new(0.8336, 1.0215, 0.4550), Tris = 232, Color = Color3.fromRGB(150, 155, 165), Material = Enum.Material.Metal },
	["NinjaShin__Strap"] = { Center = Vector3.new(0.0000, -0.0100, 0.0000), Size = Vector3.new(1.2600, 0.9000, 1.2600), Tris = 768, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
	["NinjaShin__Wrap"] = { Center = Vector3.new(0.0000, -0.0560, 0.0000), Size = Vector3.new(1.2499, 1.0119, 1.2499), Tris = 384, Color = Color3.fromRGB(40, 40, 52), Material = Enum.Material.Fabric },
	["NinjaShoulder__Plate"] = { Center = Vector3.new(0.2525, 0.3714, 0.0000), Size = Vector3.new(1.1078, 0.9393, 1.4604), Tris = 1164, Color = Color3.fromRGB(150, 155, 165), Material = Enum.Material.Metal },
	["NinjaShoulder__Rim"] = { Center = Vector3.new(0.4427, 0.1675, 0.0000), Size = Vector3.new(0.7518, 0.6049, 1.4575), Tris = 444, Color = Color3.fromRGB(200, 40, 40), Material = Enum.Material.Fabric },
}
